# SPDX-License-Identifier: GPL-2.0

ifeq ($(CONFIG_MACH_XIAOMI_SM8150),y)
ifeq ($(CONFIG_BUILD_ARM64_DT_OVERLAY),y)
	dtbo-$(CONFIG_MACH_XIAOMI_RAPHAEL) += \
		raphael-sm8150-overlay.dtbo

raphael-sm8150-overlay.dtbo-base := sm8150-v2.dtb
endif
endif
